### ISSUE TITLE
BUG: stoped working after upgrading to Plasma 6.1.0

### ISSUE THREAD

**Issue by DrYak** [feschber/lan-mouse#148] opened 2024-06-27 11:27 UTC
This morning I updated both my workstation and my laptop's Tumbleweed.

New versions:
Plasma: 6.1.0
KDE Framework: 6.3.0
Qt: 6.7.2

In that environment:
- once I move the cursor to the edge, it's not taking over the other machine.
- moving the cursor back doesn't return it to the machine
- hitting the Ctrl+Alt+Shift+Super sequence doesn't work, still doesn't return the control to the machine.
The only way to return the control is to SSH into the machine and kill lan-mouse

**Comment by aksdb** [comment] 2024-06-27 11:35
Same with 6.1.1 here.

**Comment by feschber** [comment] 2024-06-27 13:20
Ah yeah, I wanted to give an update on this: I originally thought, this would be fixed in plasma 6.1.1 but there turned out to be another issue: Plasma currently does not report barrier ids which I rely on for the libei backend.

You should be able to work around this by compiling with
```sh
cargo build --release --no-default-features --features wayland,x11,xdg_desktop_portal,gtk
```

to disable the libei backend and fallback to layer-shell until it works properly.

Its going to require a workaround or implementation for barrier ids in kwin.

#140

**Comment by DrYak** [comment] 2024-06-27 19:19
Suggestion: a command line or config file option for individually enabling/disabling protocols?

(so that it would possible to, e.g., `lan-mouse --disable-libei` even if it is compiled in?)

**Comment by feschber** [comment] 2024-06-27 19:28
Yeah that is probably a good idea. As well as a `--force-backend` option

**Comment by DrYak** [comment] 2024-06-27 20:57
> You should be able to work around this by compiling with
> ```shell
> cargo build --release --no-default-features --features wayland,x11,xdg_desktop_portal,gtk
> ```

BTW, I've updated my OBS package for Tumbleweed to exclude libei.

(I hope there isn't somewhere some Tumbleweed user who was _both_ relying on my home repo project _and_ happens to run Gnome or wherever libei isn't broken :sweat_smile: ).

Of course, I'll revert this once:
 - either Plasma fixes their libei support
 - or some option would allow to disable libei at runtime instead of compile time

**Comment by feschber** [comment] 2024-06-28 09:33
Duplicate of #140

**Closed by feschber** 2024-06-28 09:33 UTC

**Comment by feschber** [comment] 2024-06-29 08:03
>  - or some option would allow to disable libei at runtime instead of compile time

You can revert now :)

**Comment by DrYak** [comment] 2024-07-31 16:10
Updated my package (after testing locally) to your release 0.9.1 and enabled back compiling libei into it.
Seems to be working nearly(*) all the time!  :+1: 

Speaking about package, once the encryption feature is addressed some time in the future, I'll try to request getting it into the main Tumbleweed repo.

(*): To be honest, I had one single occurrence of this happening on 0.9.1. But I can't reproduce, and one of the two affected machine was a chromebook-like (PineBook Pro) running Manjaro ARM stable with _Plasma 6.**0**_, so I suspect this isn't due to libei support and more probably due to the suboptimal Wifi I am currently connecting both machines - e.g. a few dropped packets having left he whole setup in a very weird state. It eventually recovered)

**Comment by feschber** [comment] 2024-08-01 09:09
Awesome, thank you!
