### ISSUE TITLE
MacOS Client: Globe Modifier sometimes gets sent / stuck

### ISSUE THREAD

**Issue by dimenus** [feschber/lan-mouse#199] opened 2024-09-12 14:04 UTC
Hello, I'm having pretty good luck with using lan-mouse between KDE (Wayland) and MacOS, however when I'm typing quickly, it sometimes it seems like the Globe modifier gets sent/stuck somehow. I have a regular US keyboard layout. I'm not sure what key is triggering that.

Server:
KDE Plasma: 6.1.5
KDE Framework: 6.5
Qt Version: 6.7.2
Kernel: 6.10.9-arch1-2
Graphics: Wayland

Client:

M3 MBP

**Comment by dimenus** [comment] 2024-09-12 14:29
Restarting the linux side does not seem to fix the issue.

[macos.log](https://github.com/user-attachments/files/16981065/macos.log)
[linux.log](https://github.com/user-attachments/files/16981080/linux.log)

**Comment by Jacoby6000** [comment] 2024-09-23 16:21
This doesn't only happen with the globe/fn key. It also does it with caps lock and probably other modifiers too.

I've been seeing this issue a lot and it makes lan-mouse nearly unusable for me... I have to turn it off any time I'm doing a presentation or anything important because it happens so frequently.

It seems to happen more often when typing quickly, though that could just be coincidence.

**Comment by feschber** [comment] 2024-09-23 17:33
I have a suspicion what going on here, could someone check if #206 fixes this problem?

Let me know, if you need help with testing that branch, you can download a debug build from https://github.com/feschber/lan-mouse/actions/runs/10999236745?pr=206

**Comment by Jacoby6000** [comment] 2024-09-23 18:02
Running commit 196d0f on the client device I still get this issue... Running it on my Linux host as well made my mac client infinitely repeat some characters, and I couldn't make it stop even after closing lan-mouse. I had to forcibly restart the mac. :sweat_smile: 

I made another comment over here: https://github.com/feschber/lan-mouse/issues/198#issuecomment-2368810598

I wonder if that'd provide some more useful context?

**Comment by Jacoby6000** [comment] 2024-09-23 18:11
Reproducing this a second time, I can see that console on the client device gets repeatedly spammed with 
```
WARN lan_mouse::server::ping_task: device not responding, releasing keys!
```

And the key is never released, even after terminating lan-mouse. Pressing the key that's held down does nothing to release it either.

**Comment by Jacoby6000** [comment] 2024-09-23 18:16
I just realized this point was never clarified: Caps-lock, fn/globe and other modifiers are being sent and stuck even when we never press them

**Comment by feschber** [comment] 2024-09-23 18:52
@Jacoby6000 could you test the [log-keypress](https://github.com/feschber/lan-mouse/tree/log-keypress) branch
and send another log from both sides?

This would tell me whether or not its a problem with the emulation or capture code.

In any case, thank you for your detailed reports!

**Comment by Jacoby6000** [comment] 2024-09-23 21:09
Alright, here's a detailed session reproducing some funkiness

Here are the exact keystrokes I entered
```
Typing some text<CR>
<CR>
Now copying the above text<UP><LeftShift+UP><LeftMeta+C><CR>
<CR>
Now pasting the text<CR>
<CR>
<LeftMeta+V>
```

And here's the actual text output from those inputs:
```
Typing some text

Now copying the above text

Now pasting th txt
```

The <CR> inputs did not register, and the <LeftMeta+V> input pasted nothing. Unsure if the lack of paste is because it failed to even copy in the first place.

You can see the `e` inputs get dropped on the last line as well.

[lan-mouse-linux-server.txt](https://github.com/user-attachments/files/17104255/lan-mouse-server.txt)

**Comment by feschber** [comment] 2024-09-24 16:16
okay this definitely seems to be an issue with the MacOS emulation code, presumably something to do with modifier keys.

**Comment by Jacoby6000** [comment] 2024-10-08 16:52
@feschber I saw that #206 got merged. Just a reminder that when I was testing on that branch, my mac got in to a state where it would hold down a key and I could not make it stop no matter what I did. I had to restart the machine to make the key stop repeating. Closing lan-mouse did not fix the issue.  My previous comment about it may not have made that clear

**Comment by feschber** [comment] 2024-10-08 17:51
That's weird, it should functionally be identical. Could you test this on the latest commit?

**Comment by feschber** [comment] 2024-10-25 20:58
In my testing this resolves the issue at least with the command and option keys. I am however unsure about the globe modifier.

From my testing on the input-capture side, the globe modifier does not get picked up at all, (there seems to be no keycode associated with it atm) so it technically should not even work at all right now.

Would be great, if you could test this PR (#219) @Jacoby6000 @zhurai

**Comment by feschber** [comment] 2024-10-25 21:01
And in case you notice: I'm aware that caps lock does not work correctly. Will have to fix that as well

**Comment by feschber** [comment] 2024-10-27 07:41
I will merge this for now, as it definitely fixes _some_ of the problems with modifier keys in my testing.
Feel free to reopen if something does not work!

**Closed** 2024-10-27 07:41 UTC
